name: Deploy to Fly.io
on: [push]
  # push:
  #   branches:
  #     - main
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        - run: flyctl deploy --remote-only
        - uses: slackapi/slack-github-action@v1.21.0
          env:
            COLOUR: ${{ job.status == 'success' && '#22bb33' || '#bb2124' }}
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          with:
            channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
            payload: |
              {
                "attachments": [
                  {
                    "color": "$COLOUR",
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "text": "A new production deployment has been created.",
                          "type": "mrkdwn"
                        },
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Status*"
                          },
                          {
                            "type": "plain_text",
                            "text": " "
                          },
                          {
                            "type": "plain_text",
                            "text": "{{ job.status }}"
                          },
                          {
                            "type": "plain_text",
                            "text": " "
                          }
                        ]
                      }
                    ]
                  }
                ]
              }