name: Deploy to Fly.io
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
        - name: Send Slack Notification
          if: always()
          uses: slackapi/slack-github-action@v1.21.0
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          with:
            channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
            payload: |
              {
                "text": "*${{ github.event.head_commit.message }}* ${{ job.status == 'success' && 'deployed successfully.' || 'failed.' }}",
                "attachments": [
                  {
                    "color": "${{ job.status == 'success' && '#22bb33' || '#bb2124' }}",
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "text": "Details:",
                          "type": "mrkdwn"
                        },
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Status*"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Commit*"
                          },
                          {
                            "type": "plain_text",
                            "text": "${{ job.status == 'success' && '#Completed' || 'Failed' }}"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "`${{ github.sha }}`"
                          }
                        ]
                      }
                    ]
                  }
                ]
              }